### ISSUE TITLE
legato-Service-AirVantageConnector not correctly setted for 17.07-release ?

### ISSUE THREAD

**Issue by gwilga** [legatoproject/manifest#4]
https://github.com/legatoproject/manifest/blob/f748debc1b143f08f2108aa11cde9bc93d65e12a/legato/branches/17.07-release.xml#L38

I wonder if the project **legato-Service-AirVantageConnector** should not point to _**refs/heads/17.07-release**_ and not to _**refs/heads/master**_ ?

**Comment by CoRfr** [comment]
That's right, this problem has now been fixed.
